name: Convert Documentation
on: [push]

jobs:
  convert-documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-xetex

      - name: Create output directories
        run: |
          mkdir -p results/pdf
          mkdir -p results/word

      - name: Prepare files
        run: |
          # Créer un dossier temporaire
          mkdir -p temp
          # Copier les fichiers MD et les images dans le dossier temp
          cp docs/*.md temp/
          cp -r docs/images temp/
          # Modifier les chemins des images dans les fichiers MD
          for file in temp/*.md; do
            sed -i 's|/docs/images/|images/|g' "$file"
          done

      - name: Convert MD to PDF and DOCX
        working-directory: temp
        run: |
          for file in *.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .md)
              echo "Converting $file..."
              
              # Convert to PDF
              pandoc "$file" \
                -f markdown \
                -t pdf \
                --pdf-engine=xelatex \
                -o "../results/pdf/${filename}.pdf"
              
              # Convert to DOCX
              pandoc "$file" \
                -f markdown \
                -t docx \
                -o "../results/word/${filename}.docx"
            fi
          done

      - name: Upload PDF results
        uses: actions/upload-artifact@v3
        with:
          name: pdf-documents
          path: results/pdf/

      - name: Upload WORD results
        uses: actions/upload-artifact@v3
        with:
          name: word-documents
          path: results/word/